{% include 'indexSite/header.php' %}
{% load static %}

<div class="container">

<h2>Rooms & Tariff</h2>
<!-- form -->

<div class="row">
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/8.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p><div class="btn btn-default">IDR 500.000</div></div></div></div>
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/9.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p> <div class="btn btn-default">IDR 500.000</div></div></div></div>
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/10.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p> <div class="btn btn-default">IDR 500.000</div></div></div></div>
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/11.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p> <div class="btn btn-default">IDR 500.000</div></div></div></div>
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/9.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p> <div class="btn btn-default">IDR 500.000</div></div></div></div>
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/8.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p> <div class="btn btn-default">IDR 500.000</div></div></div></div>
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/10.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p> <div class="btn btn-default">IDR 500.000</div></div></div></div>
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/11.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p> <div class="btn btn-default">IDR 500.000</div></div></div></div>
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/9.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p> <div class="btn btn-default">IDR 500.000</div></div></div></div>
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/8.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p> <div class="btn btn-default">IDR 500.000</div></div></div></div>
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/11.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p> <div class="btn btn-default">IDR 500.000</div></div></div></div>
  <div class="col-sm-6 wowload fadeInUp"><div class="rooms"><img src="{% static 'indexSite/images/photos/10.jpg' %}" class="img-responsive"><div class="info"><h3>Luxirious Suites</h3><p> Missed lovers way one vanity wishes nay but. Use shy seemed within twenty wished old few regret passed. Absolute one hastened mrs any sensible</p><div class="btn btn-default">IDR 500.000</div></div></div></div></div>  
</div>


</div>
{% include 'indexSite/footer.php' %}